// BSA Council list — seeded into councils table on startup
// Source: Troop 97 (troop97.net), cross-referenced with ScoutWiki and BSA API
// As of February 2026 — 232 local councils + 5 Greater New York sub-councils
export const BSA_COUNCILS = [
  { num: 1, name: "Greater Alabama Council", city: "Birmingham", state: "AL" },
  { num: 3, name: "Alabama-Florida Council", city: "Dothan", state: "AL" },
  { num: 4, name: "Mobile Area Council", city: "Mobile", state: "AL" },
  { num: 5, name: "Tukabatchee Area Council", city: "Montgomery", state: "AL" },
  { num: 6, name: "Black Warrior Council", city: "Tuscaloosa", state: "AL" },
  { num: 10, name: "Grand Canyon Council", city: "Scottsdale", state: "AZ" },
  { num: 11, name: "Catalina Council", city: "Tucson", state: "AZ" },
  { num: 18, name: "Natural State Council", city: "Little Rock", state: "AR" },
  { num: 23, name: "Golden Gate Area Council", city: "Pleasanton", state: "CA" },
  { num: 27, name: "Sequoia Council", city: "Fresno", state: "CA" },
  { num: 31, name: "Pacific Skyline Council", city: "Foster City", state: "CA" },
  { num: 32, name: "Long Beach Area Council", city: "Long Beach", state: "CA" },
  { num: 33, name: "Greater Los Angeles Area Council", city: "Los Angeles", state: "CA" },
  { num: 35, name: "Marin Council", city: "San Rafael", state: "CA" },
  { num: 39, name: "Orange County Council", city: "Orange", state: "CA" },
  { num: 42, name: "Piedmont Council", city: "Piedmont", state: "CA" },
  { num: 45, name: "California Inland Empire Council", city: "Redlands", state: "CA" },
  { num: 47, name: "Golden Empire Council", city: "Sacramento", state: "CA" },
  { num: 49, name: "San Diego-Imperial Council", city: "San Diego", state: "CA" },
  { num: 51, name: "Western Los Angeles County Council", city: "Van Nuys", state: "CA" },
  { num: 53, name: "Los Padres Council", city: "Santa Barbara", state: "CA" },
  { num: 55, name: "Silicon Valley Monterey Bay Council", city: "San Jose", state: "CA" },
  { num: 57, name: "Ventura County Council", city: "Camarillo", state: "CA" },
  { num: 58, name: "Verdugo Hills Council", city: "Glendale", state: "CA" },
  { num: 59, name: "Greater Yosemite Council", city: "Modesto", state: "CA" },
  { num: 60, name: "Pathway to the Rockies Council", city: "Colorado Springs", state: "CO" },
  { num: 61, name: "Greater Colorado Council", city: "Denver", state: "CO" },
  { num: 62, name: "Adventure West Council", city: "Greeley", state: "CO" },
  { num: 66, name: "Connecticut Rivers Council", city: "East Hartford", state: "CT" },
  { num: 67, name: "Greenwich Council", city: "Greenwich", state: "CT" },
  { num: 69, name: "Housatonic Council", city: "Derby", state: "CT" },
  { num: 72, name: "Connecticut Yankee Council", city: "Milford", state: "CT" },
  { num: 81, name: "Del-Mar-Va Council", city: "Dover", state: "DE" },
  { num: 82, name: "National Capital Area Council", city: "Bethesda", state: "MD" },
  { num: 83, name: "Central Florida Council", city: "Orlando", state: "FL" },
  { num: 84, name: "South Florida Council", city: "Miami Lakes", state: "FL" },
  { num: 85, name: "Gulf Stream Council", city: "Palm Beach Gardens", state: "FL" },
  { num: 87, name: "North Florida Council", city: "Jacksonville", state: "FL" },
  { num: 88, name: "Southwest Florida Council", city: "Fort Myers", state: "FL" },
  { num: 89, name: "Greater Tampa Bay Area Council", city: "Tampa", state: "FL" },
  { num: 91, name: "Chattahoochee Council", city: "Columbus", state: "GA" },
  { num: 92, name: "Atlanta Area Council", city: "Atlanta", state: "GA" },
  { num: 93, name: "Georgia-Carolina Council", city: "Augusta", state: "GA" },
  { num: 95, name: "Flint River Council", city: "Griffin", state: "GA" },
  { num: 96, name: "Central Georgia Council", city: "Macon", state: "GA" },
  { num: 98, name: "South Georgia Council", city: "Valdosta", state: "GA" },
  { num: 99, name: "Coastal Georgia Council", city: "Savannah", state: "GA" },
  { num: 100, name: "Northwest Georgia Council", city: "Rome", state: "GA" },
  { num: 101, name: "Northeast Georgia Council", city: "Jefferson", state: "GA" },
  { num: 104, name: "Aloha Council", city: "Honolulu", state: "HI" },
  { num: 106, name: "Mountain West Council", city: "Boise", state: "ID" },
  { num: 107, name: "Grand Teton Council", city: "Idaho Falls", state: "ID" },
  { num: 117, name: "Prairielands Council", city: "Champaign", state: "IL" },
  { num: 127, name: "Three Fires Council", city: "St. Charles", state: "IL" },
  { num: 129, name: "Northeast Illinois Council", city: "Vernon Hills", state: "IL" },
  { num: 133, name: "Illowa Council", city: "Davenport", state: "IA" },
  { num: 138, name: "W. D. Boyce Council", city: "Peoria", state: "IL" },
  { num: 141, name: "Mississippi Valley Council", city: "Quincy", state: "IL" },
  { num: 144, name: "Abraham Lincoln Council", city: "Springfield", state: "IL" },
  { num: 145, name: "Hoosier Trails Council", city: "Bloomington", state: "IN" },
  { num: 156, name: "Buffalo Trace Council", city: "Evansville", state: "IN" },
  { num: 157, name: "Anthony Wayne Area Council", city: "Fort Wayne", state: "IN" },
  { num: 160, name: "Crossroads of America Council", city: "Indianapolis", state: "IN" },
  { num: 162, name: "Sagamore Council", city: "Kokomo", state: "IN" },
  { num: 165, name: "La Salle Council", city: "South Bend", state: "IN" },
  { num: 172, name: "Hawkeye Area Council", city: "Cedar Falls", state: "IA" },
  { num: 173, name: "Winnebago Council", city: "Waterloo", state: "IA" },
  { num: 177, name: "Mid-Iowa Council", city: "Des Moines", state: "IA" },
  { num: 178, name: "Northeast Iowa Council", city: "Dubuque", state: "IA" },
  { num: 192, name: "Coronado Area Council", city: "Salina", state: "KS" },
  { num: 197, name: "Jayhawk Area Council", city: "Topeka", state: "KS" },
  { num: 198, name: "Quivira Council", city: "Wichita", state: "KS" },
  { num: 204, name: "Blue Grass Council", city: "Lexington", state: "KY" },
  { num: 205, name: "Lincoln Heritage Council", city: "Louisville", state: "KY" },
  { num: 209, name: "Calcasieu Area Council", city: "Lake Charles", state: "LA" },
  { num: 211, name: "Istrouma Area Council", city: "Baton Rouge", state: "LA" },
  { num: 212, name: "Evangeline Area Council", city: "Lafayette", state: "LA" },
  { num: 213, name: "Louisiana Purchase Council", city: "Monroe", state: "LA" },
  { num: 214, name: "Southeast Louisiana Council", city: "New Orleans", state: "LA" },
  { num: 215, name: "Norwela Council", city: "Shreveport", state: "LA" },
  { num: 216, name: "Katahdin Area Council", city: "Orono", state: "ME" },
  { num: 218, name: "Pine Tree Council", city: "Portland", state: "ME" },
  { num: 220, name: "Baltimore Area Council", city: "Baltimore", state: "MD" },
  { num: 224, name: "Cape Cod and Islands Council", city: "Yarmouth Port", state: "MA" },
  { num: 227, name: "Spirit of Adventure Council", city: "Woburn", state: "MA" },
  { num: 230, name: "Heart of New England Council", city: "Lancaster", state: "MA" },
  { num: 234, name: "Western Massachusetts Council", city: "Holyoke", state: "MA" },
  { num: 250, name: "Northern Star Council", city: "St. Paul", state: "MN" },
  { num: 251, name: "Mayflower Council", city: "Milford", state: "MA" },
  { num: 283, name: "Twin Valley Council", city: "Mankato", state: "MN" },
  { num: 296, name: "Central Minnesota Council", city: "Sartell", state: "MN" },
  { num: 299, name: "Gamehaven Council", city: "Rochester", state: "MN" },
  { num: 302, name: "Choctaw Area Council", city: "Meridian", state: "MS" },
  { num: 303, name: "Andrew Jackson Council", city: "Flowood", state: "MS" },
  { num: 304, name: "Pine Burr Area Council", city: "Hattiesburg", state: "MS" },
  { num: 306, name: "Ozark Trails Council", city: "Springfield", state: "MO" },
  { num: 307, name: "Heart of America Council", city: "Kansas City", state: "MO" },
  { num: 311, name: "Pony Express Council", city: "St. Joseph", state: "MO" },
  { num: 312, name: "Greater St. Louis Area Council", city: "St. Louis", state: "MO" },
  { num: 315, name: "Montana Council", city: "Great Falls", state: "MT" },
  { num: 324, name: "Cornhusker Council", city: "Lincoln", state: "NE" },
  { num: 326, name: "Mid-America Council", city: "Omaha", state: "NE" },
  { num: 328, name: "Las Vegas Area Council", city: "Las Vegas", state: "NV" },
  { num: 329, name: "Nevada Area Council", city: "Reno", state: "NV" },
  { num: 330, name: "Daniel Webster Council", city: "Manchester", state: "NH" },
  { num: 333, name: "Northern New Jersey Council", city: "Oakland", state: "NJ" },
  { num: 341, name: "Jersey Shore Council", city: "Toms River", state: "NJ" },
  { num: 347, name: "Monmouth Council", city: "Morganville", state: "NJ" },
  { num: 358, name: "Patriots' Path Council", city: "Cedar Knolls", state: "NJ" },
  { num: 364, name: "Twin Rivers Council", city: "Albany", state: "NY" },
  { num: 368, name: "Baden-Powell Council", city: "Binghamton", state: "NY" },
  { num: 373, name: "Longhouse Council", city: "Syracuse", state: "NY" },
  { num: 380, name: "Great Falls Council", city: "Buffalo", state: "NY" },
  { num: 382, name: "Allegheny Highlands Council", city: "Falconer", state: "NY" },
  { num: 386, name: "Theodore Roosevelt Council", city: "Massapequa", state: "NY" },
  { num: 388, name: "Greater Hudson Valley Council", city: "Stony Point", state: "NY" },
  { num: 397, name: "Seneca Waterways Council", city: "Rochester", state: "NY" },
  { num: 400, name: "Leatherstocking Council", city: "Utica", state: "NY" },
  { num: 404, name: "Suffolk County Council", city: "Farmingville", state: "NY" },
  { num: 412, name: "High Desert Council", city: "Albuquerque", state: "NM" },
  { num: 413, name: "Conquistador Council", city: "Roswell", state: "NM" },
  { num: 414, name: "Daniel Boone Council", city: "Asheville", state: "NC" },
  { num: 415, name: "Mecklenburg County Council", city: "Charlotte", state: "NC" },
  { num: 416, name: "Central North Carolina Council", city: "Albemarle", state: "NC" },
  { num: 420, name: "Piedmont Council", city: "Gastonia", state: "NC" },
  { num: 421, name: "Occoneechee Council", city: "Raleigh", state: "NC" },
  { num: 424, name: "Tuscarora Council", city: "Goldsboro", state: "NC" },
  { num: 425, name: "Cape Fear Council", city: "Wilmington", state: "NC" },
  { num: 426, name: "East Carolina Council", city: "Kinston", state: "NC" },
  { num: 427, name: "Old Hickory Council", city: "Winston-Salem", state: "NC" },
  { num: 429, name: "Northern Lights Council", city: "Fargo", state: "ND" },
  { num: 433, name: "Great Trail Council", city: "Akron", state: "OH" },
  { num: 436, name: "Buckeye Council", city: "Canton", state: "OH" },
  { num: 438, name: "Dan Beard Council", city: "Cincinnati", state: "OH" },
  { num: 439, name: "Tecumseh Council", city: "Springfield", state: "OH" },
  { num: 440, name: "Lake Erie Council", city: "Cleveland", state: "OH" },
  { num: 441, name: "Simon Kenton Council", city: "Columbus", state: "OH" },
  { num: 444, name: "Miami Valley Council", city: "Dayton", state: "OH" },
  { num: 449, name: "Black Swamp Area Council", city: "Findlay", state: "OH" },
  { num: 456, name: "Pathway to Adventure Council", city: "Chicago", state: "IL" },
  { num: 460, name: "Erie Shores Council", city: "Toledo", state: "OH" },
  { num: 467, name: "Muskingum Valley Council", city: "Zanesville", state: "OH" },
  { num: 468, name: "Arbuckle Area Council", city: "Ardmore", state: "OK" },
  { num: 469, name: "Cherokee Area Council", city: "Bartlesville", state: "OK" },
  { num: 480, name: "Last Frontier Council", city: "Oklahoma City", state: "OK" },
  { num: 488, name: "Indian Nations Council", city: "Tulsa", state: "OK" },
  { num: 492, name: "Cascade Pacific Council", city: "Portland", state: "OR" },
  { num: 497, name: "Juniata Valley Council", city: "Reedsville", state: "PA" },
  { num: 500, name: "Moraine Trails Council", city: "Butler", state: "PA" },
  { num: 501, name: "Northeastern Pennsylvania Council", city: "Moosic", state: "PA" },
  { num: 502, name: "Minsi Trails Council", city: "Allentown", state: "PA" },
  { num: 504, name: "Columbia-Montour Council", city: "Bloomsburg", state: "PA" },
  { num: 509, name: "Bucktail Council", city: "Dubois", state: "PA" },
  { num: 512, name: "Westmoreland-Fayette Council", city: "Greensburg", state: "PA" },
  { num: 524, name: "Pennsylvania Dutch Council", city: "Lancaster", state: "PA" },
  { num: 525, name: "Cradle of Liberty Council", city: "Philadelphia", state: "PA" },
  { num: 527, name: "Laurel Highlands Council", city: "Pittsburgh", state: "PA" },
  { num: 528, name: "Hawk Mountain Council", city: "Reading", state: "PA" },
  { num: 532, name: "French Creek Council", city: "Erie", state: "PA" },
  { num: 533, name: "Susquehanna Council", city: "Williamsport", state: "PA" },
  { num: 538, name: "Chief Cornplanter Council", city: "Warren", state: "PA" },
  { num: 539, name: "Chester County Council", city: "Exton", state: "PA" },
  { num: 544, name: "New Birth of Freedom Council", city: "Mechanicsburg", state: "PA" },
  { num: 546, name: "Narragansett Council", city: "Cranston", state: "RI" },
  { num: 549, name: "Palmetto Council", city: "Spartanburg", state: "SC" },
  { num: 550, name: "Coastal Carolina Council", city: "Charleston", state: "SC" },
  { num: 551, name: "Blue Ridge Council", city: "Greenville", state: "SC" },
  { num: 553, name: "Indian Waters Council", city: "Columbia", state: "SC" },
  { num: 556, name: "Cherokee Area Council", city: "Chattanooga", state: "TN" },
  { num: 557, name: "Great Smoky Mountain Council", city: "Knoxville", state: "TN" },
  { num: 558, name: "Chickasaw Council", city: "Memphis", state: "TN" },
  { num: 559, name: "West Tennessee Area Council", city: "Jackson", state: "TN" },
  { num: 560, name: "Middle Tennessee Council", city: "Nashville", state: "TN" },
  { num: 561, name: "Texas Trails Council", city: "Abilene", state: "TX" },
  { num: 562, name: "Golden Spread Council", city: "Amarillo", state: "TX" },
  { num: 564, name: "Capitol Area Council", city: "Austin", state: "TX" },
  { num: 567, name: "Buffalo Trail Council", city: "Midland", state: "TX" },
  { num: 571, name: "Circle Ten Council", city: "Dallas", state: "TX" },
  { num: 573, name: "Yucca Council", city: "El Paso", state: "TX" },
  { num: 574, name: "Bay Area Council", city: "Galveston", state: "TX" },
  { num: 576, name: "Sam Houston Area Council", city: "Houston", state: "TX" },
  { num: 577, name: "South Texas Council", city: "Corpus Christi", state: "TX" },
  { num: 578, name: "Three Rivers Council", city: "Beaumont", state: "TX" },
  { num: 583, name: "Alamo Area Council", city: "San Antonio", state: "TX" },
  { num: 584, name: "Caddo Area Council", city: "Texarkana", state: "TX" },
  { num: 585, name: "East Texas Area Council", city: "Tyler", state: "TX" },
  { num: 587, name: "Northwest Texas Council", city: "Wichita Falls", state: "TX" },
  { num: 590, name: "Crossroads of the West Council", city: "Ogden", state: "UT" },
  { num: 592, name: "Green Mountain Council", city: "Waterbury", state: "VT" },
  { num: 595, name: "Colonial Virginia Council", city: "Newport News", state: "VA" },
  { num: 596, name: "Tidewater Council", city: "Virginia Beach", state: "VA" },
  { num: 598, name: "Shenandoah Area Council", city: "Winchester", state: "VA" },
  { num: 599, name: "Blue Ridge Mountains Council", city: "Roanoke", state: "VA" },
  { num: 602, name: "Heart of Virginia Council", city: "Richmond", state: "VA" },
  { num: 604, name: "Blue Mountain Council", city: "Kennewick", state: "WA" },
  { num: 606, name: "Mount Baker Council", city: "Everett", state: "WA" },
  { num: 609, name: "Chief Seattle Council", city: "Seattle", state: "WA" },
  { num: 610, name: "Great Alaska Council", city: "Anchorage", state: "AK" },
  { num: 611, name: "Inland Northwest Council", city: "Spokane", state: "WA" },
  { num: 612, name: "Pacific Harbors Council", city: "Tacoma", state: "WA" },
  { num: 615, name: "Mountaineer Area Council", city: "Wheeling", state: "WV" },
  { num: 617, name: "Buckskin Council", city: "Charleston", state: "WV" },
  { num: 620, name: "Glacier's Edge Council", city: "Madison", state: "WI" },
  { num: 624, name: "Gateway Area Council", city: "La Crosse", state: "WI" },
  { num: 627, name: "Samoset Council", city: "Weston", state: "WI" },
  { num: 635, name: "Bay-Lakes Council", city: "Appleton", state: "WI" },
  { num: 636, name: "Three Harbors Council", city: "Milwaukee", state: "WI" },
  { num: 637, name: "Chippewa Valley Council", city: "Eau Claire", state: "WI" },
  { num: 640, name: "Greater New York Councils", city: "New York", state: "NY" },
  { num: 641, name: "Bronx Council", city: "New York", state: "NY" },
  { num: 642, name: "Brooklyn Council", city: "Brooklyn", state: "NY" },
  { num: 643, name: "Manhattan Council", city: "New York", state: "NY" },
  { num: 644, name: "Queens Council", city: "New York", state: "NY" },
  { num: 645, name: "Staten Island Council", city: "Richmond", state: "NY" },
  { num: 651, name: "Potawatomi Area Council", city: "Waukesha", state: "WI" },
  { num: 653, name: "Great Rivers Council", city: "Columbia", state: "MO" },
  { num: 660, name: "Blackhawk Area Council", city: "Rockford", state: "IL" },
  { num: 661, name: "Puerto Rico Council", city: "Guaynabo", state: "PR" },
  { num: 662, name: "Longhorn Council", city: "Fort Worth", state: "TX" },
  { num: 664, name: "Suwannee River Area Council", city: "Tallahassee", state: "FL" },
  { num: 690, name: "Garden State Council", city: "Westampton", state: "NJ" },
  { num: 694, name: "South Plains Council", city: "Lubbock", state: "TX" },
  { num: 695, name: "Black Hills Area Council", city: "Rapid City", state: "SD" },
  { num: 696, name: "Midnight Sun Council", city: "Fairbanks", state: "AK" },
  { num: 697, name: "Pacific Crest Council", city: "Eugene", state: "OR" },
  { num: 702, name: "Rainbow Council", city: "Morris", state: "IL" },
  { num: 713, name: "Sequoyah Council", city: "Johnson City", state: "TN" },
  { num: 733, name: "Sioux Council", city: "Sioux Falls", state: "SD" },
  { num: 741, name: "Texas Southwest Council", city: "San Angelo", state: "TX" },
  { num: 748, name: "Natchez Trace Council", city: "Tupelo", state: "MS" },
  { num: 763, name: "Virginia Headwaters Council", city: "Staunton", state: "VA" },
  { num: 770, name: "Old North State Council", city: "Greensboro", state: "NC" },
  { num: 773, name: "Gulf Coast Council", city: "Pensacola", state: "FL" },
  { num: 775, name: "Rio Grande Council", city: "Harlingen", state: "TX" },
  { num: 777, name: "Washington Crossing Council", city: "Doylestown", state: "PA" },
  { num: 780, name: "Michigan Crossroads Council", city: "Eagle", state: "MI" },
  { num: 802, name: "Transatlantic Council", city: "Brussels", state: "BE" },
  { num: 803, name: "Far East Council", city: "Okinawa", state: "JP" },
];
