// BSA Council list — seeded into councils table on startup
// Source: Boy Scouts of America council directory
export const BSA_COUNCILS = [
  { name: "Alamo Area Council", city: "San Antonio", state: "TX" },
  { name: "Alaska Council", city: "Anchorage", state: "AK" },
  { name: "Aloha Council", city: "Honolulu", state: "HI" },
  { name: "Andrew Jackson Council", city: "Jackson", state: "MS" },
  { name: "Anthony Wayne Area Council", city: "Fort Wayne", state: "IN" },
  { name: "Arbuckle Area Council", city: "Ardmore", state: "OK" },
  { name: "Arizona Crossroads Council", city: "Mesa", state: "AZ" },
  { name: "Atlanta Area Council", city: "Atlanta", state: "GA" },
  { name: "Baltimore Area Council", city: "Baltimore", state: "MD" },
  { name: "Bay Area Council", city: "Houston", state: "TX" },
  { name: "Bay-Lakes Council", city: "Appleton", state: "WI" },
  { name: "Black Swamp Area Council", city: "Findlay", state: "OH" },
  { name: "Blue Grass Council", city: "Lexington", state: "KY" },
  { name: "Blue Mountain Council", city: "Walla Walla", state: "WA" },
  { name: "Blue Ridge Council", city: "Greenville", state: "SC" },
  { name: "Bluegrass Council", city: "Louisville", state: "KY" },
  { name: "Boy Scouts of America, Japan", city: "Camp Zama", state: "AP" },
  { name: "Buckeye Council", city: "Canton", state: "OH" },
  { name: "Buckskin Council", city: "Charleston", state: "WV" },
  { name: "Buffalo Trail Council", city: "Midland", state: "TX" },
  { name: "Calcasieu Area Council", city: "Lake Charles", state: "LA" },
  { name: "Cape Fear Council", city: "Wilmington", state: "NC" },
  { name: "Capitol Area Council", city: "Austin", state: "TX" },
  { name: "Cascade Pacific Council", city: "Portland", state: "OR" },
  { name: "Catalina Council", city: "Tucson", state: "AZ" },
  { name: "Central Florida Council", city: "Orlando", state: "FL" },
  { name: "Central Georgia Council", city: "Macon", state: "GA" },
  { name: "Central Indiana Council", city: "Indianapolis", state: "IN" },
  { name: "Central Minnesota Council", city: "St. Cloud", state: "MN" },
  { name: "Central New Jersey Council", city: "New Brunswick", state: "NJ" },
  { name: "Central North Carolina Council", city: "Greensboro", state: "NC" },
  { name: "Chattahoochee Council", city: "Columbus", state: "GA" },
  { name: "Cherokee Area Council", city: "Kingsport", state: "TN" },
  { name: "Chestnut Ridge Council", city: "Latrobe", state: "PA" },
  { name: "Chickasaw Council", city: "Memphis", state: "TN" },
  { name: "Chief Cornplanter Council", city: "Olean", state: "NY" },
  { name: "Chief Seattle Council", city: "Seattle", state: "WA" },
  { name: "Cimarron Council", city: "Ponca City", state: "OK" },
  { name: "Circle Ten Council", city: "Dallas", state: "TX" },
  { name: "Coastal Carolina Council", city: "Charleston", state: "SC" },
  { name: "Coastal Georgia Council", city: "Savannah", state: "GA" },
  { name: "Colonial Virginia Council", city: "Newport News", state: "VA" },
  { name: "Connecticut Rivers Council", city: "East Hartford", state: "CT" },
  { name: "Connecticut Yankee Council", city: "Milford", state: "CT" },
  { name: "Cornhusker Council", city: "Omaha", state: "NE" },
  { name: "Coronado Area Council", city: "Salina", state: "KS" },
  { name: "Cradle of Liberty Council", city: "Philadelphia", state: "PA" },
  { name: "Crossroads of America Council", city: "Indianapolis", state: "IN" },
  { name: "Dan Beard Council", city: "Cincinnati", state: "OH" },
  { name: "Daniel Boone Council", city: "Asheville", state: "NC" },
  { name: "Daniel Webster Council", city: "Manchester", state: "NH" },
  { name: "Del-Mar-Va Council", city: "Wilmington", state: "DE" },
  { name: "Denali Council", city: "Fairbanks", state: "AK" },
  { name: "Desert Pacific Council", city: "San Diego", state: "CA" },
  { name: "Direct Service Council", city: "Irving", state: "TX" },
  { name: "East Carolina Council", city: "Kinston", state: "NC" },
  { name: "East Texas Area Council", city: "Tyler", state: "TX" },
  { name: "Erie Shores Council", city: "Sandusky", state: "OH" },
  { name: "Evangeline Area Council", city: "Lafayette", state: "LA" },
  { name: "Far East Council", city: "Camp Humphreys", state: "AP" },
  { name: "Flint River Council", city: "Griffin", state: "GA" },
  { name: "French Creek Council", city: "Meadville", state: "PA" },
  { name: "Garden State Council", city: "Bordentown", state: "NJ" },
  { name: "Gateway Area Council", city: "Peoria", state: "IL" },
  { name: "Georgia-Carolina Council", city: "Augusta", state: "GA" },
  { name: "Glacier's Edge Council", city: "Madison", state: "WI" },
  { name: "Golden Empire Council", city: "Sacramento", state: "CA" },
  { name: "Golden Spread Council", city: "Amarillo", state: "TX" },
  { name: "Grand Canyon Council", city: "Phoenix", state: "AZ" },
  { name: "Grand Teton Council", city: "Idaho Falls", state: "ID" },
  { name: "Great Alaska Council", city: "Anchorage", state: "AK" },
  { name: "Great Lakes Council", city: "Kalamazoo", state: "MI" },
  { name: "Great Plains Council", city: "Oklahoma City", state: "OK" },
  { name: "Great Rivers Council", city: "Quincy", state: "IL" },
  { name: "Great Salt Lake Council", city: "Salt Lake City", state: "UT" },
  { name: "Great Smoky Mountain Council", city: "Knoxville", state: "TN" },
  { name: "Great Southwest Council", city: "Las Cruces", state: "NM" },
  { name: "Great Trail Council", city: "Akron", state: "OH" },
  { name: "Greater Alabama Council", city: "Birmingham", state: "AL" },
  { name: "Greater Cleveland Council", city: "Cleveland", state: "OH" },
  { name: "Greater Colorado Council", city: "Denver", state: "CO" },
  { name: "Greater Hudson Valley Council", city: "Newburgh", state: "NY" },
  { name: "Greater Los Angeles Area Council", city: "Los Angeles", state: "CA" },
  { name: "Greater New York Councils", city: "New York", state: "NY" },
  { name: "Greater Niagara Frontier Council", city: "Tonawanda", state: "NY" },
  { name: "Greater St. Louis Area Council", city: "St. Louis", state: "MO" },
  { name: "Greater Tampa Bay Area Council", city: "Tampa", state: "FL" },
  { name: "Greater Wyoming Council", city: "Casper", state: "WY" },
  { name: "Greater Yosemite Council", city: "Modesto", state: "CA" },
  { name: "Green Mountain Council", city: "Waterbury", state: "VT" },
  { name: "Gulf Coast Council", city: "Mobile", state: "AL" },
  { name: "Gulf Stream Council", city: "Palm Beach Gardens", state: "FL" },
  { name: "Hanover Area Council", city: "Hanover", state: "PA" },
  { name: "Hawk Mountain Council", city: "Reading", state: "PA" },
  { name: "Hawkeye Area Council", city: "Cedar Rapids", state: "IA" },
  { name: "Heart of America Council", city: "Kansas City", state: "MO" },
  { name: "Heart of Virginia Council", city: "Richmond", state: "VA" },
  { name: "Heartland Council", city: "Kansas City", state: "KS" },
  { name: "Hiawatha Seaway Council", city: "Syracuse", state: "NY" },
  { name: "Hudson Valley Council", city: "Wappingers Falls", state: "NY" },
  { name: "Illowa Council", city: "Rock Island", state: "IL" },
  { name: "Indian Nations Council", city: "Tulsa", state: "OK" },
  { name: "Indian Waters Council", city: "Columbia", state: "SC" },
  { name: "Inland Northwest Council", city: "Spokane", state: "WA" },
  { name: "Istrouma Area Council", city: "Baton Rouge", state: "LA" },
  { name: "Jayhawk Area Council", city: "Topeka", state: "KS" },
  { name: "Jersey Shore Council", city: "Toms River", state: "NJ" },
  { name: "Katahdin Area Council", city: "Bangor", state: "ME" },
  { name: "Kenosha Council", city: "Kenosha", state: "WI" },
  { name: "Lake Erie Council", city: "Erie", state: "PA" },
  { name: "Lakeshore Council", city: "Muskegon", state: "MI" },
  { name: "Laurel Highlands Council", city: "Pittsburgh", state: "PA" },
  { name: "Leatherstocking Council", city: "Utica", state: "NY" },
  { name: "Lincoln Heritage Council", city: "Louisville", state: "KY" },
  { name: "Lincoln Trails Council", city: "Decatur", state: "IL" },
  { name: "Lone Star Council", city: "Waco", state: "TX" },
  { name: "Long Horn Council", city: "Fort Worth", state: "TX" },
  { name: "Longhouse Council", city: "Baldwinsville", state: "NY" },
  { name: "Louisiana Purchase Council", city: "Metairie", state: "LA" },
  { name: "Marin Council", city: "San Rafael", state: "CA" },
  { name: "Mason-Dixon Council", city: "Hagerstown", state: "MD" },
  { name: "Michigan Crossroads Council", city: "Lansing", state: "MI" },
  { name: "Middle Tennessee Council", city: "Nashville", state: "TN" },
  { name: "Mid-America Council", city: "Omaha", state: "NE" },
  { name: "Mid-Iowa Council", city: "Des Moines", state: "IA" },
  { name: "Minnow Brook Council", city: "Syracuse", state: "NY" },
  { name: "Mississippi Valley Council", city: "Davenport", state: "IA" },
  { name: "Monmouth Council", city: "Morganville", state: "NJ" },
  { name: "Montana Council", city: "Great Falls", state: "MT" },
  { name: "Moraine Trails Council", city: "Butler", state: "PA" },
  { name: "Mount Baker Council", city: "Bellingham", state: "WA" },
  { name: "Mountain West Council", city: "Reno", state: "NV" },
  { name: "Mountaineer Area Council", city: "Elkins", state: "WV" },
  { name: "Muscogee Council", city: "Dothan", state: "AL" },
  { name: "Muskingum Valley Council", city: "Zanesville", state: "OH" },
  { name: "Narragansett Council", city: "Providence", state: "RI" },
  { name: "Nashville Council", city: "Nashville", state: "TN" },
  { name: "National Capital Area Council", city: "Bethesda", state: "MD" },
  { name: "Nevada Area Council", city: "Reno", state: "NV" },
  { name: "New Birth of Freedom Council", city: "Mechanicsburg", state: "PA" },
  { name: "New England Base Camp Council", city: "Pawtucket", state: "RI" },
  { name: "Northeast Georgia Council", city: "Gainesville", state: "GA" },
  { name: "Northeast Illinois Council", city: "Chicago", state: "IL" },
  { name: "Northeast Iowa Council", city: "Dubuque", state: "IA" },
  { name: "Northern Lights Council", city: "St. Paul", state: "MN" },
  { name: "Northern New Jersey Council", city: "Oakland", state: "NJ" },
  { name: "Northern Star Council", city: "St. Paul", state: "MN" },
  { name: "Northern Tier National High Adventure", city: "Ely", state: "MN" },
  { name: "Northwest Suburban Council", city: "Arlington Heights", state: "IL" },
  { name: "Northwest Texas Council", city: "Lubbock", state: "TX" },
  { name: "Occoneechee Council", city: "Raleigh", state: "NC" },
  { name: "Ohio River Valley Council", city: "Evansville", state: "IN" },
  { name: "Old Hickory Council", city: "Nashville", state: "TN" },
  { name: "Old North State Council", city: "Charlotte", state: "NC" },
  { name: "Orange County Council", city: "Costa Mesa", state: "CA" },
  { name: "Ore-Ida Council", city: "Boise", state: "ID" },
  { name: "Oregon Trail Council", city: "Salem", state: "OR" },
  { name: "Ozark Trails Council", city: "Springfield", state: "MO" },
  { name: "Pacific Harbor Council", city: "Tacoma", state: "WA" },
  { name: "Pacific Skyline Council", city: "San Mateo", state: "CA" },
  { name: "Palmetto Council", city: "Spartanburg", state: "SC" },
  { name: "Palo Alto Council", city: "Palo Alto", state: "CA" },
  { name: "Pathfinder Council", city: "Springfield", state: "IL" },
  { name: "Patriot's Path Council", city: "Chatham", state: "NJ" },
  { name: "Pee Dee Area Council", city: "Florence", state: "SC" },
  { name: "Piedmont Council", city: "Gastonia", state: "NC" },
  { name: "Pine Burr Area Council", city: "Hattiesburg", state: "MS" },
  { name: "Pine Tree Council", city: "Portland", state: "ME" },
  { name: "Pioneer Council", city: "Kitchener", state: "ON" },
  { name: "Pioneers Council", city: "St. Joseph", state: "MO" },
  { name: "Ponca Area Council", city: "Ponca City", state: "OK" },
  { name: "Potawatomi Area Council", city: "Waukesha", state: "WI" },
  { name: "Prairielands Council", city: "Bloomington", state: "IL" },
  { name: "Puerto Rico Council", city: "San Juan", state: "PR" },
  { name: "Quapaw Area Council", city: "Little Rock", state: "AR" },
  { name: "Rainbow Council", city: "Joliet", state: "IL" },
  { name: "Redwood Empire Council", city: "Santa Rosa", state: "CA" },
  { name: "Rio Grande Council", city: "Harlingen", state: "TX" },
  { name: "Rocky Mountain Council", city: "Missoula", state: "MT" },
  { name: "Sam Houston Area Council", city: "Houston", state: "TX" },
  { name: "San Diego-Imperial Council", city: "San Diego", state: "CA" },
  { name: "San Gabriel Valley Council", city: "Pasadena", state: "CA" },
  { name: "Santa Clara County Council", city: "San Jose", state: "CA" },
  { name: "Sawtooth Council", city: "Boise", state: "ID" },
  { name: "Seneca Waterways Council", city: "Rochester", state: "NY" },
  { name: "Sequoia Council", city: "Fresno", state: "CA" },
  { name: "Sequoyah Council", city: "Chattanooga", state: "TN" },
  { name: "Simon Kenton Council", city: "Springfield", state: "OH" },
  { name: "Snake River Council", city: "Boise", state: "ID" },
  { name: "South Florida Council", city: "Miami", state: "FL" },
  { name: "South Plains Council", city: "Lubbock", state: "TX" },
  { name: "South Texas Council", city: "Corpus Christi", state: "TX" },
  { name: "Southeast Louisiana Council", city: "Metairie", state: "LA" },
  { name: "Southern Sierra Council", city: "Bakersfield", state: "CA" },
  { name: "Southwest Florida Council", city: "Fort Myers", state: "FL" },
  { name: "Spirit of Adventure Council", city: "Stoneham", state: "MA" },
  { name: "Susquehanna Council", city: "Harrisburg", state: "PA" },
  { name: "Suwannee River Area Council", city: "Live Oak", state: "FL" },
  { name: "Tecumseh Council", city: "Springfield", state: "IL" },
  { name: "Tennessee Valley Council", city: "Huntsville", state: "AL" },
  { name: "Teton Peaks Council", city: "Pocatello", state: "ID" },
  { name: "Texas Trails Council", city: "Abilene", state: "TX" },
  { name: "Theodore Roosevelt Council", city: "Massapequa", state: "NY" },
  { name: "Three Fires Council", city: "St. Charles", state: "IL" },
  { name: "Three Harbors Council", city: "Racine", state: "WI" },
  { name: "Three Rivers Council", city: "Fort Wayne", state: "IN" },
  { name: "Tidewater Council", city: "Virginia Beach", state: "VA" },
  { name: "Timpanogos Council", city: "Provo", state: "UT" },
  { name: "Trapper Trails Council", city: "Ogden", state: "UT" },
  { name: "Tri-Rivers District Council", city: "Columbus", state: "OH" },
  { name: "Tuscarora Council", city: "Goldsboro", state: "NC" },
  { name: "Twin Rivers Council", city: "Gonzales", state: "LA" },
  { name: "Twin Valley Council", city: "West Chester", state: "PA" },
  { name: "Utah National Parks Council", city: "Provo", state: "UT" },
  { name: "Ventura County Council", city: "Camarillo", state: "CA" },
  { name: "Viking Council", city: "Minneapolis", state: "MN" },
  { name: "Virginia Headwaters Council", city: "Staunton", state: "VA" },
  { name: "Voyageurs Area Council", city: "Duluth", state: "MN" },
  { name: "W. D. Boyce Council", city: "Peoria", state: "IL" },
  { name: "Washington Crossing Council", city: "Doylestown", state: "PA" },
  { name: "Watchung Area Council", city: "Berkeley Heights", state: "NJ" },
  { name: "West Michigan Shores Council", city: "Muskegon", state: "MI" },
  { name: "Western Colorado Council", city: "Grand Junction", state: "CO" },
  { name: "Western Massachusetts Council", city: "Springfield", state: "MA" },
  { name: "Westmoreland-Fayette Council", city: "Greensburg", state: "PA" },
  { name: "Winnebago Council", city: "Oshkosh", state: "WI" },
  { name: "Yocona Area Council", city: "Oxford", state: "MS" },
  { name: "Yokahu Council", city: "San Juan", state: "PR" },
  { name: "York-Adams Area Council", city: "York", state: "PA" },
];
