import Logo from "./Logo";

export default function PrintCheatSheet({ adventure, itinerary, onClose }) {
  if (!itinerary) return null;
  const route = itinerary.route_data || [];
  const global = itinerary.global_info || {};
  const totalMiles = route.reduce((s, d) => s + d.miles, 0);

  const print = (type) => {
    const w = window.open("", "_blank");
    if (!w) return;
    const dates = [adventure?.depart_date, adventure?.arrive_date, adventure?.return_date, adventure?.home_date].filter(Boolean);
    const dateRange = dates.length >= 2 ? `${dates[0]} to ${dates[dates.length - 1]}` : dates[0] || "";

    const pocketHTML = `
      <h2 style="margin:0 0 4px">${adventure?.name || itinerary.name}</h2>
      <p style="margin:0 0 8px;font-size:11px;color:#666">${dateRange} | ${totalMiles.toFixed(0)} mi total | ${route.length} days</p>
      <table style="width:100%;border-collapse:collapse;font-size:10px">
        <thead><tr style="background:#f5f5f5">
          <th style="padding:3px 4px;text-align:left;border-bottom:1px solid #ccc">Day</th>
          <th style="padding:3px 4px;text-align:left;border-bottom:1px solid #ccc">Camp</th>
          <th style="padding:3px 4px;text-align:right;border-bottom:1px solid #ccc">Mi</th>
          <th style="padding:3px 4px;text-align:right;border-bottom:1px solid #ccc">Elev</th>
          <th style="padding:3px 4px;text-align:left;border-bottom:1px solid #ccc">Type</th>
          <th style="padding:3px 4px;text-align:left;border-bottom:1px solid #ccc">Notes</th>
        </tr></thead>
        <tbody>${route.map(d => `
          <tr style="border-bottom:1px solid #eee${d.type === 'Dry Camp' ? ';background:#fff8f0' : ''}">
            <td style="padding:2px 4px;font-weight:bold">${d.day}</td>
            <td style="padding:2px 4px">${d.camp}</td>
            <td style="padding:2px 4px;text-align:right">${d.miles}</td>
            <td style="padding:2px 4px;text-align:right">${d.elevation ? d.elevation.toLocaleString() + "'" : ""}</td>
            <td style="padding:2px 4px;font-size:9px">${d.type || ""}</td>
            <td style="padding:2px 4px;font-size:9px;max-width:140px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">${d.notes || ""}</td>
          </tr>
        `).join("")}</tbody>
      </table>
      <div style="margin-top:8px;font-size:9px;color:#888">
        <strong>DRY CAMPS:</strong> ${route.filter(d => d.type === "Dry Camp").map(d => `Day ${d.day} (${d.camp})`).join(", ") || "None"}
        ${global.prohibited_items ? `<br><strong>PROHIBITED:</strong> ${global.prohibited_items.slice(0, 5).join(", ")}` : ""}
      </div>
    `;

    const fullHTML = `
      <div style="display:flex;align-items:center;gap:12px;margin-bottom:12px;border-bottom:2px solid #2a3d2e;padding-bottom:8px">
        <div>
          <h1 style="margin:0;font-size:20px;color:#2a3d2e">${adventure?.name || itinerary.name}</h1>
          <p style="margin:2px 0 0;font-size:12px;color:#666">${dateRange}</p>
        </div>
      </div>

      ${pocketHTML}

      ${route.some(d => d.water) ? `
        <h3 style="margin:12px 0 4px;font-size:13px;color:#8a6d3b">Water Strategy</h3>
        <div style="font-size:10px">${route.filter(d => d.water).map(d =>
          `<div style="margin-bottom:4px"><strong>Day ${d.day} (${d.camp}):</strong> ${d.water.strategy || ""}${d.water.carry_liters ? ` — Carry ${d.water.carry_liters}L min` : ""}</div>`
        ).join("")}</div>
      ` : ""}

      ${route.some(d => d.programs?.length) ? `
        <h3 style="margin:12px 0 4px;font-size:13px;color:#4a7a55">Programs</h3>
        <div style="font-size:10px">${route.filter(d => d.programs?.length).map(d =>
          `<div style="margin-bottom:3px"><strong>Day ${d.day}:</strong> ${d.programs.map(p => p.name).join(", ")}</div>`
        ).join("")}</div>
      ` : ""}

      ${global.prohibited_items ? `
        <h3 style="margin:12px 0 4px;font-size:13px;color:#c03030">Prohibited Items</h3>
        <div style="font-size:10px">${global.prohibited_items.map(i => `<span style="margin-right:8px">&#x2717; ${i}</span>`).join("")}</div>
      ` : ""}

      ${global.conservation_project ? `
        <h3 style="margin:12px 0 4px;font-size:13px;color:#4a7a55">Conservation Project — Day ${global.conservation_project.day}</h3>
        <div style="font-size:10px">${global.conservation_project.description || ""}</div>
      ` : ""}

      <div style="margin-top:12px;font-size:9px;color:#aaa;text-align:center">Generated by TrekSync — treksync.gracezero.ai</div>
    `;

    w.document.write(`<!DOCTYPE html><html><head><title>${adventure?.name || "Trek"} Cheat Sheet</title>
      <style>body{font-family:Arial,sans-serif;padding:20px;max-width:750px;margin:0 auto}@media print{body{padding:10px}}</style>
    </head><body>${type === "pocket" ? pocketHTML : fullHTML}</body></html>`);
    w.document.close();
    setTimeout(() => w.print(), 300);
  };

  return (
    <div style={{ position: "fixed", inset: 0, background: "rgba(0,0,0,0.7)", display: "flex", alignItems: "center", justifyContent: "center", zIndex: 999 }} onClick={onClose}>
      <div onClick={e => e.stopPropagation()} style={{ background: "#1a2420", borderRadius: 12, padding: 24, width: 300, textAlign: "center", boxShadow: "0 8px 32px rgba(0,0,0,0.3)", border: "1px solid #3d5a45" }}>
        <Logo size={40} />
        <h3 style={{ color: "#d4c8a8", margin: "12px 0 6px", fontFamily: "Georgia, serif" }}>Print Itinerary</h3>
        <p style={{ color: "#8a9a8a", fontSize: 12, marginBottom: 16 }}>No cell phones on the trail — take a paper copy!</p>
        <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
          <button onClick={() => print("pocket")} style={{ padding: "10px 0", borderRadius: 8, border: "none", background: "#4a7a55", color: "#fff", fontSize: 13, fontWeight: 600, cursor: "pointer" }}>
            Print Pocket Card
          </button>
          <button onClick={() => print("full")} style={{ padding: "10px 0", borderRadius: 8, border: "1px solid #4a7a55", background: "transparent", color: "#7aba7a", fontSize: 13, fontWeight: 600, cursor: "pointer" }}>
            Print Full Summary
          </button>
          <button onClick={onClose} style={{ padding: "8px 0", borderRadius: 8, border: "1px solid #3d5a45", background: "transparent", color: "#8a9a8a", fontSize: 12, cursor: "pointer", marginTop: 4 }}>
            Cancel
          </button>
        </div>
      </div>
    </div>
  );
}
